import * as fs from "node:fs";
import * as path from "node:path";
import type { CodeIntelConfig, CodeIntelFileOutlineParams, CodeIntelRepoOverviewParams, CodeIntelTestMapParams, ResultDetail } from "../../types.ts";
import { LANGUAGE_CAPABILITIES, LANGUAGE_SPECS, languageCapability, languageSpec } from "../../languages.ts";
import { collectRepoFiles } from "../../file-discovery.ts";
import { importsFor } from "../../language-support/imports.ts";
import { ensureInsideRoot } from "../../repo.ts";
import { runReferenceConfirmation } from "../../lsp/confirmation.ts";
import { rowWithTarget } from "../../source-range.ts";
import { extractFileRecords, parseFiles, readSourceFileAsParsed, type SymbolRecord } from "../../tree-sitter.ts";
import { candidateScore, defaultTestPaths, shouldConsiderTestCandidate, testMapTerms, testSearchPaths } from "../test-map/language-heuristics.ts";
import { normalizePositiveInteger, normalizeStringArray, summarizeFileDistribution } from "../../util.ts";

const DEFAULT_EXCLUDED_DIRS = new Set([".git", ".hg", ".svn", "node_modules", "vendor", "dist", "out", "target", ".cache", "build", "build_debug", "build_release", "cmake-build-debug", "cmake-build-release"]);
const VENDOR_DIRS = new Set(["contrib", "third_party", "3rdparty", "external", "externals", "vendor"]);
const GENERATED_DIRS = new Set(["generated", "gen", "autogenerated", "__pycache__"]);
const DOC_EXTENSIONS = new Set([".md", ".mdc", ".rst", ".txt", ".adoc"]);
const CONFIG_NAMES = new Set(["package.json", "tsconfig.json", "CMakeLists.txt", "Makefile", "Dockerfile", "compose.yml", "docker-compose.yml", ".clangd"]);
const TEST_DIR_PATTERN = /(^|\/)(__tests__|test|tests|spec|integration|gtest|queries|stateless)(\/|$)/i;
const TEST_FILE_PATTERN = /(^|\/).*(\.test|\.spec)\.[cm]?[tj]sx?$|(^|\/).*_test\.(go|rs)$|(^|\/)test_.*\.py$/i;

interface ScanFile {
	path: string;
	absolutePath: string;
	language?: string;
	category: "source" | "test" | "doc" | "config" | "other";
	extension: string;
}

interface ScanDirectory {
	path: string;
	depth: number;
	dirs: number;
	files: number;
	sourceFiles: number;
	testFiles: number;
	docFiles: number;
	configFiles: number;
	otherFiles: number;
	languages: Map<string, number>;
	children: ScanDirectory[];
	fileEntries: ScanFile[];
	truncated: boolean;
}

interface ScanResult {
	roots: string[];
	directories: ScanDirectory[];
	files: ScanFile[];
	diagnostics: string[];
	excludedDirs: Record<string, number>;
	truncated: boolean;
	dirsVisited: number;
	filesVisited: number;
}

function posixPath(value: string): string {
	return value.split(path.sep).join(path.posix.sep);
}

function repoRelative(repoRoot: string, absolutePath: string): string {
	const rel = path.relative(repoRoot, absolutePath);
	return rel ? posixPath(rel) : ".";
}

function isIgnoredDir(name: string, includeVendor: boolean, includeGenerated: boolean): boolean {
	if (DEFAULT_EXCLUDED_DIRS.has(name)) return true;
	if (!includeVendor && VENDOR_DIRS.has(name)) return true;
	if (!includeGenerated && GENERATED_DIRS.has(name)) return true;
	return false;
}

function fileLanguage(file: string): string | undefined {
	const ext = path.extname(file);
	return LANGUAGE_CAPABILITIES.find((capability) => capability.extensions.includes(ext))?.id;
}

function fileCategory(file: string, language?: string): ScanFile["category"] {
	const base = path.posix.basename(file);
	const ext = path.extname(base);
	if (TEST_DIR_PATTERN.test(file) || TEST_FILE_PATTERN.test(file)) return "test";
	if (DOC_EXTENSIONS.has(ext)) return "doc";
	if (CONFIG_NAMES.has(base) || base.endsWith(".config.ts") || base.endsWith(".config.js") || base.endsWith(".toml") || base.endsWith(".yaml") || base.endsWith(".yml")) return "config";
	if (language) return "source";
	return "other";
}

function safeInputPaths(repoRoot: string, paths: string[] | undefined, diagnostics: string[]): string[] {
	const roots = paths && paths.length > 0 ? paths : ["."];
	const output: string[] = [];
	for (const item of roots) {
		try {
			output.push(ensureInsideRoot(repoRoot, item));
		} catch (error) {
			diagnostics.push(`${item}: ${error instanceof Error ? error.message : String(error)}`);
		}
	}
	return output;
}

function dominantLanguages(map: Map<string, number>, max = 5): Array<{ language: string; files: number }> {
	return [...map.entries()].sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0])).slice(0, max).map(([language, files]) => ({ language, files }));
}

function emptyDir(relativePath: string, depth: number): ScanDirectory {
	return { path: relativePath, depth, dirs: 0, files: 0, sourceFiles: 0, testFiles: 0, docFiles: 0, configFiles: 0, otherFiles: 0, languages: new Map(), children: [], fileEntries: [], truncated: false };
}

function addFileStats(dir: ScanDirectory, file: ScanFile): void {
	dir.files++;
	if (file.category === "source") dir.sourceFiles++;
	else if (file.category === "test") dir.testFiles++;
	else if (file.category === "doc") dir.docFiles++;
	else if (file.category === "config") dir.configFiles++;
	else dir.otherFiles++;
	if (file.language) dir.languages.set(file.language, (dir.languages.get(file.language) ?? 0) + 1);
}

function serializeDirectory(dir: ScanDirectory, includeFiles: boolean, maxSymbolsPerFile: number, declarationsByFile: Map<string, unknown[]>): Record<string, unknown> {
	const output: Record<string, unknown> = {
		path: dir.path,
		depth: dir.depth,
		dirs: dir.dirs,
		files: dir.files,
		sourceFiles: dir.sourceFiles,
		testFiles: dir.testFiles,
		docFiles: dir.docFiles,
		configFiles: dir.configFiles,
		otherFiles: dir.otherFiles,
		dominantLanguages: dominantLanguages(dir.languages),
		truncated: dir.truncated,
	};
	if (dir.children.length > 0) output.children = dir.children.map((child) => serializeDirectory(child, false, maxSymbolsPerFile, declarationsByFile));
	if (includeFiles) {
		output.fileEntries = dir.fileEntries.map((file) => ({ path: file.path, language: file.language, category: file.category, declarations: (declarationsByFile.get(file.path) ?? []).slice(0, maxSymbolsPerFile), truncated: (declarationsByFile.get(file.path) ?? []).length > maxSymbolsPerFile }));
	}
	return output;
}

function globToRegExp(glob: string): RegExp {
	const normalized = glob.startsWith("!") ? glob.slice(1) : glob;
	let output = "^";
	for (let index = 0; index < normalized.length; index++) {
		const char = normalized[index];
		const next = normalized[index + 1];
		if (char === "*" && next === "*") {
			output += ".*";
			index++;
		} else if (char === "*") output += "[^/]*";
		else if (char === "?") output += "[^/]";
		else output += char.replace(/[|\\{}()[\]^$+?.]/g, "\\$&");
	}
	return new RegExp(`${output}$`);
}

function matchesAnyGlob(file: string, globs: string[]): boolean {
	return globs.some((glob) => globToRegExp(glob).test(file));
}

function includeByGlobs(file: string, includeGlobs: string[], excludeGlobs: string[]): boolean {
	const excludes = excludeGlobs.map((glob) => glob.startsWith("!") ? glob.slice(1) : glob);
	if (includeGlobs.length > 0 && !matchesAnyGlob(file, includeGlobs)) return false;
	return excludes.length === 0 || !matchesAnyGlob(file, excludes);
}

function scanExcludedDirs(includeVendor: boolean, includeGenerated: boolean): Set<string> {
	const dirs = new Set(DEFAULT_EXCLUDED_DIRS);
	if (!includeVendor) for (const dir of VENDOR_DIRS) dirs.add(dir);
	if (!includeGenerated) for (const dir of GENERATED_DIRS) dirs.add(dir);
	return dirs;
}

function fileUnderRoot(file: string, root: string): boolean {
	if (root === "." || root === "") return true;
	return file === root || file.startsWith(`${root.replace(/\/$/, "")}/`);
}

function relativeToRoot(file: string, root: string): string {
	if (root === "." || root === "") return file;
	if (file === root) return path.posix.basename(file);
	return file.slice(root.replace(/\/$/, "").length + 1);
}

function scanRepo(repoRoot: string, params: { paths?: string[]; maxDepth: number; maxDirs: number; maxFilesPerDir: number; includeVendor: boolean; includeGenerated: boolean; includeIgnored?: boolean; includeGlobs?: string[]; excludeGlobs?: string[]; timeoutMs: number }, signal?: AbortSignal): ScanResult {
	const diagnostics: string[] = [];
	const excludedDirNames = scanExcludedDirs(params.includeVendor, params.includeGenerated);
	const discovered = collectRepoFiles(repoRoot, {
		paths: params.paths,
		includeGlobs: params.includeGlobs,
		excludeGlobs: params.excludeGlobs,
		includeIgnored: params.includeIgnored === true,
		excludedDirNames,
		timeoutMs: params.timeoutMs,
		diagnostics,
		signal,
	});
	const files: ScanFile[] = discovered.files.map((file) => {
		const language = fileLanguage(file.file);
		return { path: file.file, absolutePath: file.absolute, language, category: fileCategory(file.file, language), extension: path.extname(file.file) };
	});
	const excludedDirs = { ...discovered.excludedDirs };
	const countExcludedDirs = (absoluteDir: string, depth: number): void => {
		if (depth > params.maxDepth || signal?.aborted) return;
		let entries: fs.Dirent[];
		try {
			entries = fs.readdirSync(absoluteDir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			if (!entry.isDirectory()) continue;
			if (excludedDirNames.has(entry.name)) excludedDirs[entry.name] = (excludedDirs[entry.name] ?? 0) + 1;
			else countExcludedDirs(path.join(absoluteDir, entry.name), depth + 1);
		}
	};
	for (const root of discovered.roots) {
		const absolute = path.resolve(repoRoot, root);
		if (fs.existsSync(absolute) && fs.statSync(absolute).isDirectory()) countExcludedDirs(absolute, 0);
	}
	let dirsVisited = 0;
	let truncated = discovered.truncated;

	const createDir = (relativePath: string, depth: number): ScanDirectory | undefined => {
		if (dirsVisited >= params.maxDirs) {
			truncated = true;
			return undefined;
		}
		dirsVisited++;
		return emptyDir(relativePath, depth);
	};

	const addToDirectory = (dir: ScanDirectory, root: string, file: ScanFile, parts: string[], depth: number): void => {
		addFileStats(dir, file);
		if (parts.length === 1) {
			if (dir.fileEntries.length < params.maxFilesPerDir) dir.fileEntries.push(file);
			else if (params.maxFilesPerDir > 0) {
				dir.truncated = true;
				truncated = true;
			}
			return;
		}
		if (depth >= params.maxDepth) {
			dir.truncated = true;
			truncated = true;
			return;
		}
		const childName = parts[0];
		const childPath = dir.path === "." ? childName : `${dir.path}/${childName}`;
		let child = dir.children.find((candidate) => candidate.path === childPath);
		if (!child) {
			child = createDir(childPath, depth + 1);
			if (!child) {
				dir.truncated = true;
				return;
			}
			dir.children.push(child);
			dir.dirs++;
		}
		addToDirectory(child, root, file, parts.slice(1), depth + 1);
		if (child.truncated) dir.truncated = true;
	};

	const directories: ScanDirectory[] = [];
	for (const root of discovered.roots) {
		const absolute = path.resolve(repoRoot, root);
		if (!fs.existsSync(absolute) || !fs.statSync(absolute).isDirectory()) continue;
		const dir = createDir(root, 0);
		if (!dir) break;
		for (const file of files.filter((candidate) => fileUnderRoot(candidate.path, root))) {
			const relative = relativeToRoot(file.path, root);
			const parts = relative.split("/").filter(Boolean);
			if (parts.length === 0) continue;
			addToDirectory(dir, root, file, parts, 0);
		}
		directories.push(dir);
	}

	return {
		roots: discovered.roots,
		directories,
		files,
		diagnostics,
		excludedDirs,
		truncated,
		dirsVisited,
		filesVisited: files.length,
	};
}

function declarationRows(records: SymbolRecord[], detail: ResultDetail, source?: string, repoRoot?: string): Record<string, unknown>[] {
	return records.map((record) => {
		const row = rowWithTarget(record, source, repoRoot, records);
		if (detail !== "snippets") delete row.text;
		return row;
	});
}

export async function runFileOutline(params: CodeIntelFileOutlineParams, repoRoot: string, config: CodeIntelConfig, signal?: AbortSignal): Promise<Record<string, unknown>> {
	const started = Date.now();
	const diagnostics: string[] = [];
	let safeFile: string;
	try {
		safeFile = ensureInsideRoot(repoRoot, params.path);
	} catch (error) {
		return { ok: false, repoRoot, diagnostics: [error instanceof Error ? error.message : String(error)], elapsedMs: Date.now() - started };
	}
	const language = fileLanguage(safeFile);
	const capability = language ? languageCapability(language) : undefined;
	if (!language || !capability || (!languageSpec(language) && capability.parser.kind !== "scanner")) return { ok: false, repoRoot, file: safeFile, diagnostics: [`No Tree-sitter language configured for ${safeFile}`], elapsedMs: Date.now() - started };
	const timeoutMs = normalizePositiveInteger(params.timeoutMs, config.queryTimeoutMs, 1_000, 600_000);
	const maxSymbols = normalizePositiveInteger(params.maxSymbols, 250, 1, 1_000);
	const detail: ResultDetail = params.detail === "snippets" ? "snippets" : "locations";
	const parsed = capability.parser.kind === "scanner" ? { parsedFiles: [readSourceFileAsParsed(repoRoot, safeFile, language)], diagnostics: [], filesByLanguage: { [language]: 1 }, parsedByLanguage: { [language]: 1 } } : await parseFiles(repoRoot, [language], [safeFile], [], [], timeoutMs, signal);
	const parsedFile = parsed.parsedFiles.find((file) => file.file === safeFile);
	if (!parsedFile) return { ok: false, repoRoot, file: safeFile, language, diagnostics: parsed.diagnostics.length ? parsed.diagnostics : [`${safeFile}: file could not be parsed`], elapsedMs: Date.now() - started };
	let records: SymbolRecord[] = [];
	try {
		records = extractFileRecords(parsedFile, detail).definitions;
	} catch (error) {
		diagnostics.push(`${safeFile}: Tree-sitter record extraction failed: ${error instanceof Error ? error.message : String(error)}`);
	}
	const declarations = declarationRows(records, detail, parsedFile.source, repoRoot);
	return {
		ok: true,
		repoRoot,
		file: safeFile,
		language,
		sourceIncluded: false,
		sourceCompleteness: "locations-only",
		nextReadRecommended: true,
		nextReadReason: "source-not-included",
		imports: params.includeImports === false ? undefined : importsFor(language, parsedFile.source),
		declarations: declarations.slice(0, maxSymbols),
		summary: { declarationCount: declarations.length, importCount: params.includeImports === false ? undefined : importsFor(language, parsedFile.source).length },
		coverage: { truncated: declarations.length > maxSymbols, maxSymbols },
		diagnostics: [...parsed.diagnostics, ...diagnostics],
		limitations: ["File outlines are Tree-sitter syntax evidence for navigation, not semantic proof of API boundaries or references."],
		elapsedMs: Date.now() - started,
	};
}

export async function runRepoOverview(params: CodeIntelRepoOverviewParams, repoRoot: string, config: CodeIntelConfig, signal?: AbortSignal): Promise<Record<string, unknown>> {
	const started = Date.now();
	const tier = params.tier === "files" ? "files" : "shape";
	const maxDepth = normalizePositiveInteger(params.maxDepth, tier === "shape" ? 2 : 3, 0, 12);
	const maxDirs = normalizePositiveInteger(params.maxDirs, tier === "shape" ? 200 : 80, 1, 2_000);
	const maxFilesPerDir = normalizePositiveInteger(params.maxFilesPerDir, tier === "shape" ? 1 : 80, 0, 1_000);
	const maxSymbolsPerFile = normalizePositiveInteger(params.maxSymbolsPerFile, 8, 0, 100);
	const timeoutMs = normalizePositiveInteger(params.timeoutMs, config.queryTimeoutMs, 1_000, 600_000);
	const scan = scanRepo(repoRoot, { paths: params.paths, maxDepth, maxDirs, maxFilesPerDir, includeVendor: params.includeVendor === true, includeGenerated: params.includeGenerated === true, includeIgnored: params.includeIgnored === true, includeGlobs: normalizeStringArray(params.includeGlobs), excludeGlobs: normalizeStringArray(params.excludeGlobs), timeoutMs }, signal);
	const declarationsByFile = new Map<string, unknown[]>();
	let parsedCount = 0;
	if (tier === "files" && maxSymbolsPerFile > 0) {
		const filesToParse = scan.files.filter((file) => file.language && file.category !== "doc" && file.category !== "config").slice(0, scan.directories.length * maxFilesPerDir || maxFilesPerDir);
		const byLanguage = new Map<string, string[]>();
		for (const file of filesToParse) {
			if (!file.language) continue;
			const bucket = byLanguage.get(file.language) ?? [];
			bucket.push(file.path);
			byLanguage.set(file.language, bucket);
		}
		for (const [language, files] of byLanguage) {
			const parsed = await parseFiles(repoRoot, [language], files, [], [], timeoutMs, signal);
			scan.diagnostics.push(...parsed.diagnostics);
			parsedCount += parsed.parsedFiles.length;
			for (const parsedFile of parsed.parsedFiles) {
				try {
					const rows = declarationRows(extractFileRecords(parsedFile, "locations").definitions, "locations", parsedFile.source, repoRoot);
					declarationsByFile.set(parsedFile.file, rows);
				} catch (error) {
					scan.diagnostics.push(`${parsedFile.file}: Tree-sitter record extraction failed: ${error instanceof Error ? error.message : String(error)}`);
				}
			}
		}
	}
	const serialized = scan.directories.map((dir) => serializeDirectory(dir, tier === "files", maxSymbolsPerFile, declarationsByFile));
	return {
		ok: true,
		repoRoot,
		tier,
		sourceIncluded: false,
		sourceCompleteness: "locations-only",
		nextReadRecommended: tier === "files",
		nextReadReason: tier === "files" ? "source-not-included" : "filesystem-shape-only",
		roots: scan.roots,
		directories: serialized,
		summary: { dirCount: scan.dirsVisited, fileCount: scan.filesVisited, sourceFileCount: scan.files.filter((file) => file.category === "source").length, testFileCount: scan.files.filter((file) => file.category === "test").length, parsedFileCount: parsedCount },
		coverage: { maxDepth, maxDirs, maxFilesPerDir, maxSymbolsPerFile, truncated: scan.truncated, excludedDirs: scan.excludedDirs, includeIgnored: params.includeIgnored === true },
		diagnostics: scan.diagnostics,
		limitations: [tier === "shape" ? "Shape overview is filesystem evidence only; use tier:'files' or code_intel_file_outline for declarations." : "File-tier overview is capped per directory and per file; use code_intel_file_outline for a complete single-file outline."],
		elapsedMs: Date.now() - started,
	};
}

export async function runTestMap(params: CodeIntelTestMapParams, repoRoot: string, config: CodeIntelConfig, signal?: AbortSignal): Promise<Record<string, unknown>> {
	const started = Date.now();
	const maxResults = normalizePositiveInteger(params.maxResults, Math.min(config.maxResults, 50), 1, 500);
	const maxLiteralMatches = normalizePositiveInteger(params.maxLiteralMatches, 5, 0, 50);
	const timeoutMs = normalizePositiveInteger(params.timeoutMs, config.queryTimeoutMs, 1_000, 600_000);
	const diagnostics: string[] = [];
	let safePath: string | undefined;
	if (params.path) {
		try {
			safePath = ensureInsideRoot(repoRoot, params.path);
		} catch (error) {
			diagnostics.push(`${params.path}: ${error instanceof Error ? error.message : String(error)}`);
		}
	}
	const sourceLanguage = safePath ? fileLanguage(safePath) : undefined;
	const explicitTerms = [...new Set([...normalizeStringArray(params.symbols), ...normalizeStringArray(params.names)].filter((term) => term.length >= 2))];
	const terms = testMapTerms(safePath, explicitTerms);
	const shapeScan = scanRepo(repoRoot, { paths: ["."], maxDepth: 4, maxDirs: 500, maxFilesPerDir: 0, includeVendor: false, includeGenerated: false, includeIgnored: params.includeIgnored === true, timeoutMs }, signal);
	const explicitTestPaths = normalizeStringArray(params.testPaths);
	const testRoots = explicitTestPaths.length > 0 ? explicitTestPaths : defaultTestPaths(shapeScan);
	const searchPaths = explicitTestPaths.length > 0 ? explicitTestPaths : testSearchPaths(testRoots, safePath, sourceLanguage);
	const scan = scanRepo(repoRoot, { paths: searchPaths, maxDepth: 12, maxDirs: 1_000, maxFilesPerDir: 1_000, includeVendor: false, includeGenerated: false, includeIgnored: params.includeIgnored === true, timeoutMs }, signal);
	const candidates: Array<Record<string, unknown> & { score: number; evidence: Record<string, unknown>[] }> = [];
	for (const file of scan.files) {
		if (!shouldConsiderTestCandidate(file, sourceLanguage)) continue;
		const scored = candidateScore(file, { targetPath: safePath, terms, explicitTerms, sourceLanguage, maxLiteralMatches });
		if (scored.score <= 0 || scored.evidence.length === 0) continue;
		candidates.push({ file: file.path, language: file.language, category: file.category, score: scored.score, evidence: scored.evidence });
	}
	candidates.sort((left, right) => right.score - left.score || String(left.file).localeCompare(String(right.file)));
	const outputCandidates = candidates.slice(0, maxResults);
	const output: Record<string, unknown> = {
		ok: true,
		repoRoot,
		target: { path: safePath, symbols: normalizeStringArray(params.symbols), names: normalizeStringArray(params.names) },
		candidates: outputCandidates,
		summary: { candidateCount: candidates.length, returnedCount: outputCandidates.length, testRootsSearched: testRoots },
		coverage: { truncated: candidates.length > maxResults, maxResults, maxLiteralMatches, searchedFileCount: scan.files.length, excludedDirs: { ...shapeScan.excludedDirs, ...scan.excludedDirs }, includeIgnored: params.includeIgnored === true },
		diagnostics: [...diagnostics, ...shapeScan.diagnostics, ...scan.diagnostics],
		limitations: ["Test maps are evidence-ranked candidates, not exhaustive coverage proof. Non-code tests may only match path or literal terms."],
		elapsedMs: Date.now() - started,
	};
	if (params.confirmReferences === "gopls" || params.confirmReferences === "typescript" || params.confirmReferences === "clangd" || params.confirmReferences === "rust-analyzer" || params.confirmReferences === "csharp-ls" || params.confirmReferences === "pyrefly") {
		const outline = safePath ? await runFileOutline({ path: safePath, maxSymbols: 20, detail: "locations" }, repoRoot, config, signal) : undefined;
		const roots = Array.isArray(outline?.declarations) ? (outline.declarations as Record<string, unknown>[]).filter((row) => normalizeStringArray(params.symbols).includes(String(row.name))).map((row) => ({ name: String(row.name), file: safePath ?? "", language: String(outline?.language ?? ""), kind: String(row.kind ?? "definition"), line: Number(row.line ?? 1), column: Number(row.column ?? 1), endLine: Number(row.endLine ?? row.line ?? 1), endColumn: Number(row.endColumn ?? row.column ?? 1) })) : [];
		output.referenceConfirmation = await runReferenceConfirmation(params.confirmReferences, roots, repoRoot, { maxRoots: params.maxReferenceRoots, maxResults: params.maxReferenceResults, timeoutMs, includeDeclarations: false }, config, signal);
	}
	return output;
}
