import * as fs from "node:fs";
import * as path from "node:path";
import type { CodeIntelConfig, CodeIntelFileOutlineParams, CodeIntelRepoOverviewParams, CodeIntelTestMapParams, ResultDetail } from "./types.ts";
import { LANGUAGE_SPECS, languageSpec } from "./languages.ts";
import { ensureInsideRoot } from "./repo.ts";
import { runReferenceConfirmation } from "./lsp/confirmation.ts";
import { rowWithTarget } from "./source-range.ts";
import { extractFileRecords, parseFiles, type SymbolRecord } from "./tree-sitter.ts";
import { normalizePositiveInteger, normalizeStringArray, summarizeFileDistribution } from "./util.ts";

const DEFAULT_EXCLUDED_DIRS = new Set([".git", ".hg", ".svn", "node_modules", "vendor", "dist", "out", "target", ".cache", "build", "build_debug", "build_release", "cmake-build-debug", "cmake-build-release"]);
const VENDOR_DIRS = new Set(["contrib", "third_party", "3rdparty", "external", "externals", "vendor"]);
const GENERATED_DIRS = new Set(["generated", "gen", "autogenerated", "__pycache__"]);
const DOC_EXTENSIONS = new Set([".md", ".mdc", ".rst", ".txt", ".adoc"]);
const CONFIG_NAMES = new Set(["package.json", "tsconfig.json", "CMakeLists.txt", "Makefile", "Dockerfile", "compose.yml", "docker-compose.yml", ".clangd"]);
const TEST_DIR_PATTERN = /(^|\/)(__tests__|test|tests|spec|integration|gtest|queries|stateless)(\/|$)/i;
const TEST_FILE_PATTERN = /(^|\/).*(\.test|\.spec)\.[cm]?[tj]sx?$|(^|\/).*_test\.(go|rs)$|(^|\/)test_.*\.py$/i;

interface ScanFile {
	path: string;
	absolutePath: string;
	language?: string;
	category: "source" | "test" | "doc" | "config" | "other";
	extension: string;
}

interface ScanDirectory {
	path: string;
	depth: number;
	dirs: number;
	files: number;
	sourceFiles: number;
	testFiles: number;
	docFiles: number;
	configFiles: number;
	otherFiles: number;
	languages: Map<string, number>;
	children: ScanDirectory[];
	fileEntries: ScanFile[];
	truncated: boolean;
}

interface ScanResult {
	roots: string[];
	directories: ScanDirectory[];
	files: ScanFile[];
	diagnostics: string[];
	excludedDirs: Record<string, number>;
	truncated: boolean;
	dirsVisited: number;
	filesVisited: number;
}

function posixPath(value: string): string {
	return value.split(path.sep).join(path.posix.sep);
}

function repoRelative(repoRoot: string, absolutePath: string): string {
	const rel = path.relative(repoRoot, absolutePath);
	return rel ? posixPath(rel) : ".";
}

function isIgnoredDir(name: string, includeVendor: boolean, includeGenerated: boolean): boolean {
	if (DEFAULT_EXCLUDED_DIRS.has(name)) return true;
	if (!includeVendor && VENDOR_DIRS.has(name)) return true;
	if (!includeGenerated && GENERATED_DIRS.has(name)) return true;
	return false;
}

function fileLanguage(file: string): string | undefined {
	const ext = path.extname(file);
	return LANGUAGE_SPECS.find((spec) => spec.extensions.includes(ext))?.id;
}

function fileCategory(file: string, language?: string): ScanFile["category"] {
	const base = path.posix.basename(file);
	const ext = path.extname(base);
	if (TEST_DIR_PATTERN.test(file) || TEST_FILE_PATTERN.test(file)) return "test";
	if (DOC_EXTENSIONS.has(ext)) return "doc";
	if (CONFIG_NAMES.has(base) || base.endsWith(".config.ts") || base.endsWith(".config.js") || base.endsWith(".toml") || base.endsWith(".yaml") || base.endsWith(".yml")) return "config";
	if (language) return "source";
	return "other";
}

function safeInputPaths(repoRoot: string, paths: string[] | undefined, diagnostics: string[]): string[] {
	const roots = paths && paths.length > 0 ? paths : ["."];
	const output: string[] = [];
	for (const item of roots) {
		try {
			output.push(ensureInsideRoot(repoRoot, item));
		} catch (error) {
			diagnostics.push(`${item}: ${error instanceof Error ? error.message : String(error)}`);
		}
	}
	return output;
}

function dominantLanguages(map: Map<string, number>, max = 5): Array<{ language: string; files: number }> {
	return [...map.entries()].sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0])).slice(0, max).map(([language, files]) => ({ language, files }));
}

function emptyDir(relativePath: string, depth: number): ScanDirectory {
	return { path: relativePath, depth, dirs: 0, files: 0, sourceFiles: 0, testFiles: 0, docFiles: 0, configFiles: 0, otherFiles: 0, languages: new Map(), children: [], fileEntries: [], truncated: false };
}

function addFileStats(dir: ScanDirectory, file: ScanFile): void {
	dir.files++;
	if (file.category === "source") dir.sourceFiles++;
	else if (file.category === "test") dir.testFiles++;
	else if (file.category === "doc") dir.docFiles++;
	else if (file.category === "config") dir.configFiles++;
	else dir.otherFiles++;
	if (file.language) dir.languages.set(file.language, (dir.languages.get(file.language) ?? 0) + 1);
}

function serializeDirectory(dir: ScanDirectory, includeFiles: boolean, maxSymbolsPerFile: number, declarationsByFile: Map<string, unknown[]>): Record<string, unknown> {
	const output: Record<string, unknown> = {
		path: dir.path,
		depth: dir.depth,
		dirs: dir.dirs,
		files: dir.files,
		sourceFiles: dir.sourceFiles,
		testFiles: dir.testFiles,
		docFiles: dir.docFiles,
		configFiles: dir.configFiles,
		otherFiles: dir.otherFiles,
		dominantLanguages: dominantLanguages(dir.languages),
		truncated: dir.truncated,
	};
	if (dir.children.length > 0) output.children = dir.children.map((child) => serializeDirectory(child, false, maxSymbolsPerFile, declarationsByFile));
	if (includeFiles) {
		output.fileEntries = dir.fileEntries.map((file) => ({ path: file.path, language: file.language, category: file.category, declarations: (declarationsByFile.get(file.path) ?? []).slice(0, maxSymbolsPerFile), truncated: (declarationsByFile.get(file.path) ?? []).length > maxSymbolsPerFile }));
	}
	return output;
}

function globToRegExp(glob: string): RegExp {
	const normalized = glob.startsWith("!") ? glob.slice(1) : glob;
	let output = "^";
	for (let index = 0; index < normalized.length; index++) {
		const char = normalized[index];
		const next = normalized[index + 1];
		if (char === "*" && next === "*") {
			output += ".*";
			index++;
		} else if (char === "*") output += "[^/]*";
		else if (char === "?") output += "[^/]";
		else output += char.replace(/[|\\{}()[\]^$+?.]/g, "\\$&");
	}
	return new RegExp(`${output}$`);
}

function matchesAnyGlob(file: string, globs: string[]): boolean {
	return globs.some((glob) => globToRegExp(glob).test(file));
}

function includeByGlobs(file: string, includeGlobs: string[], excludeGlobs: string[]): boolean {
	const excludes = excludeGlobs.map((glob) => glob.startsWith("!") ? glob.slice(1) : glob);
	if (includeGlobs.length > 0 && !matchesAnyGlob(file, includeGlobs)) return false;
	return excludes.length === 0 || !matchesAnyGlob(file, excludes);
}

function scanRepo(repoRoot: string, params: { paths?: string[]; maxDepth: number; maxDirs: number; maxFilesPerDir: number; includeVendor: boolean; includeGenerated: boolean; includeGlobs?: string[]; excludeGlobs?: string[]; timeoutMs: number }, signal?: AbortSignal): ScanResult {
	const started = Date.now();
	const diagnostics: string[] = [];
	const roots = safeInputPaths(repoRoot, params.paths, diagnostics);
	const includeGlobs = params.includeGlobs ?? [];
	const excludeGlobs = params.excludeGlobs ?? [];
	const files: ScanFile[] = [];
	const excludedDirs: Record<string, number> = {};
	let dirsVisited = 0;
	let filesVisited = 0;
	let truncated = false;

	function scanDirectory(absoluteDir: string, depth: number): ScanDirectory {
		const relativeDir = repoRelative(repoRoot, absoluteDir);
		const dir = emptyDir(relativeDir, depth);
		if (signal?.aborted || Date.now() - started > params.timeoutMs) {
			diagnostics.push("Repository scan stopped before all paths were visited");
			dir.truncated = true;
			truncated = true;
			return dir;
		}
		dirsVisited++;
		if (dirsVisited > params.maxDirs) {
			dir.truncated = true;
			truncated = true;
			return dir;
		}
		let entries: fs.Dirent[];
		try {
			entries = fs.readdirSync(absoluteDir, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name));
		} catch (error) {
			diagnostics.push(`${relativeDir}: ${error instanceof Error ? error.message : String(error)}`);
			return dir;
		}
		for (const entry of entries) {
			const absolute = path.join(absoluteDir, entry.name);
			if (entry.isDirectory()) {
				if (isIgnoredDir(entry.name, params.includeVendor, params.includeGenerated)) {
					excludedDirs[entry.name] = (excludedDirs[entry.name] ?? 0) + 1;
					continue;
				}
				dir.dirs++;
				if (depth < params.maxDepth) dir.children.push(scanDirectory(absolute, depth + 1));
				else {
					dir.truncated = true;
					truncated = true;
				}
			} else if (entry.isFile()) {
				const relativeFile = repoRelative(repoRoot, absolute);
				if (!includeByGlobs(relativeFile, includeGlobs, excludeGlobs)) continue;
				const language = fileLanguage(relativeFile);
				const scanFile: ScanFile = { path: relativeFile, absolutePath: absolute, language, category: fileCategory(relativeFile, language), extension: path.extname(relativeFile) };
				files.push(scanFile);
				filesVisited++;
				addFileStats(dir, scanFile);
				if (dir.fileEntries.length < params.maxFilesPerDir) dir.fileEntries.push(scanFile);
				else if (params.maxFilesPerDir > 0) {
					dir.truncated = true;
					truncated = true;
				}
			}
		}
		for (const child of dir.children) {
			dir.files += child.files;
			dir.sourceFiles += child.sourceFiles;
			dir.testFiles += child.testFiles;
			dir.docFiles += child.docFiles;
			dir.configFiles += child.configFiles;
			dir.otherFiles += child.otherFiles;
			for (const [language, count] of child.languages) dir.languages.set(language, (dir.languages.get(language) ?? 0) + count);
			if (child.truncated) dir.truncated = true;
		}
		return dir;
	}

	const directories: ScanDirectory[] = [];
	for (const root of roots) {
		const absolute = path.resolve(repoRoot, root);
		if (!fs.existsSync(absolute)) {
			diagnostics.push(`${root}: path does not exist`);
			continue;
		}
		const stat = fs.statSync(absolute);
		if (stat.isDirectory()) directories.push(scanDirectory(absolute, 0));
		else if (stat.isFile()) {
			if (!includeByGlobs(root, includeGlobs, excludeGlobs)) continue;
			const language = fileLanguage(root);
			const scanFile: ScanFile = { path: root, absolutePath: absolute, language, category: fileCategory(root, language), extension: path.extname(root) };
			files.push(scanFile);
			filesVisited++;
		}
	}
	return { roots, directories, files, diagnostics, excludedDirs, truncated, dirsVisited, filesVisited };
}

function declarationRows(records: SymbolRecord[], detail: ResultDetail, source?: string, repoRoot?: string): Record<string, unknown>[] {
	return records.map((record) => {
		const row = rowWithTarget(record, source, repoRoot, records);
		if (detail !== "snippets") delete row.text;
		return row;
	});
}

function importsFor(language: string | undefined, source: string): string[] {
	const imports: string[] = [];
	for (const line of source.split(/\r?\n/)) {
		const trimmed = line.trim();
		if (!trimmed) continue;
		let match: RegExpExecArray | null = null;
		if (language === "cpp") match = /^#\s*include\s*[<"]([^>"]+)/.exec(trimmed);
		else if (language === "go") match = /^import\s+(?:[\w.]+\s+)?"([^"]+)"/.exec(trimmed);
		else if (language === "rust") match = /^(?:pub\s+)?(?:use\s+([^;]+)|mod\s+([A-Za-z_][\w]*))\s*;/.exec(trimmed);
		else if (language === "python") match = /^(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))/.exec(trimmed);
		else match = /^import\s+(?:.+?\s+from\s+)?["']([^"']+)["']/.exec(trimmed) ?? /^export\s+.+?\s+from\s+["']([^"']+)["']/.exec(trimmed);
		const value = match?.[1] ?? match?.[2];
		if (value) imports.push(value);
	}
	return [...new Set(imports)].slice(0, 200);
}

export async function runFileOutline(params: CodeIntelFileOutlineParams, repoRoot: string, config: CodeIntelConfig, signal?: AbortSignal): Promise<Record<string, unknown>> {
	const started = Date.now();
	const diagnostics: string[] = [];
	let safeFile: string;
	try {
		safeFile = ensureInsideRoot(repoRoot, params.path);
	} catch (error) {
		return { ok: false, repoRoot, diagnostics: [error instanceof Error ? error.message : String(error)], elapsedMs: Date.now() - started };
	}
	const language = fileLanguage(safeFile);
	if (!language || !languageSpec(language)) return { ok: false, repoRoot, file: safeFile, diagnostics: [`No Tree-sitter language configured for ${safeFile}`], elapsedMs: Date.now() - started };
	const timeoutMs = normalizePositiveInteger(params.timeoutMs, config.queryTimeoutMs, 1_000, 600_000);
	const maxSymbols = normalizePositiveInteger(params.maxSymbols, 250, 1, 1_000);
	const detail: ResultDetail = params.detail === "snippets" ? "snippets" : "locations";
	const parsed = await parseFiles(repoRoot, [language], [safeFile], [], [], timeoutMs, signal);
	const parsedFile = parsed.parsedFiles.find((file) => file.file === safeFile);
	if (!parsedFile) return { ok: false, repoRoot, file: safeFile, language, diagnostics: parsed.diagnostics.length ? parsed.diagnostics : [`${safeFile}: file could not be parsed`], elapsedMs: Date.now() - started };
	let records: SymbolRecord[] = [];
	try {
		records = extractFileRecords(parsedFile, detail).definitions;
	} catch (error) {
		diagnostics.push(`${safeFile}: Tree-sitter record extraction failed: ${error instanceof Error ? error.message : String(error)}`);
	}
	const declarations = declarationRows(records, detail, parsedFile.source, repoRoot);
	return {
		ok: true,
		repoRoot,
		file: safeFile,
		language,
		sourceIncluded: false,
		sourceCompleteness: "locations-only",
		nextReadRecommended: true,
		nextReadReason: "source-not-included",
		imports: params.includeImports === false ? undefined : importsFor(language, parsedFile.source),
		declarations: declarations.slice(0, maxSymbols),
		summary: { declarationCount: declarations.length, importCount: params.includeImports === false ? undefined : importsFor(language, parsedFile.source).length },
		coverage: { truncated: declarations.length > maxSymbols, maxSymbols },
		diagnostics: [...parsed.diagnostics, ...diagnostics],
		limitations: ["File outlines are Tree-sitter syntax evidence for navigation, not semantic proof of API boundaries or references."],
		elapsedMs: Date.now() - started,
	};
}

export async function runRepoOverview(params: CodeIntelRepoOverviewParams, repoRoot: string, config: CodeIntelConfig, signal?: AbortSignal): Promise<Record<string, unknown>> {
	const started = Date.now();
	const tier = params.tier === "files" ? "files" : "shape";
	const maxDepth = normalizePositiveInteger(params.maxDepth, tier === "shape" ? 2 : 3, 0, 12);
	const maxDirs = normalizePositiveInteger(params.maxDirs, tier === "shape" ? 200 : 80, 1, 2_000);
	const maxFilesPerDir = normalizePositiveInteger(params.maxFilesPerDir, tier === "shape" ? 1 : 80, 0, 1_000);
	const maxSymbolsPerFile = normalizePositiveInteger(params.maxSymbolsPerFile, 8, 0, 100);
	const timeoutMs = normalizePositiveInteger(params.timeoutMs, config.queryTimeoutMs, 1_000, 600_000);
	const scan = scanRepo(repoRoot, { paths: params.paths, maxDepth, maxDirs, maxFilesPerDir, includeVendor: params.includeVendor === true, includeGenerated: params.includeGenerated === true, includeGlobs: normalizeStringArray(params.includeGlobs), excludeGlobs: normalizeStringArray(params.excludeGlobs), timeoutMs }, signal);
	const declarationsByFile = new Map<string, unknown[]>();
	let parsedCount = 0;
	if (tier === "files" && maxSymbolsPerFile > 0) {
		const filesToParse = scan.files.filter((file) => file.language && file.category !== "doc" && file.category !== "config").slice(0, scan.directories.length * maxFilesPerDir || maxFilesPerDir);
		const byLanguage = new Map<string, string[]>();
		for (const file of filesToParse) {
			if (!file.language) continue;
			const bucket = byLanguage.get(file.language) ?? [];
			bucket.push(file.path);
			byLanguage.set(file.language, bucket);
		}
		for (const [language, files] of byLanguage) {
			const parsed = await parseFiles(repoRoot, [language], files, [], [], timeoutMs, signal);
			scan.diagnostics.push(...parsed.diagnostics);
			parsedCount += parsed.parsedFiles.length;
			for (const parsedFile of parsed.parsedFiles) {
				try {
					const rows = declarationRows(extractFileRecords(parsedFile, "locations").definitions, "locations", parsedFile.source, repoRoot);
					declarationsByFile.set(parsedFile.file, rows);
				} catch (error) {
					scan.diagnostics.push(`${parsedFile.file}: Tree-sitter record extraction failed: ${error instanceof Error ? error.message : String(error)}`);
				}
			}
		}
	}
	const serialized = scan.directories.map((dir) => serializeDirectory(dir, tier === "files", maxSymbolsPerFile, declarationsByFile));
	return {
		ok: true,
		repoRoot,
		tier,
		sourceIncluded: false,
		sourceCompleteness: "locations-only",
		nextReadRecommended: tier === "files",
		nextReadReason: tier === "files" ? "source-not-included" : "filesystem-shape-only",
		roots: scan.roots,
		directories: serialized,
		summary: { dirCount: scan.dirsVisited, fileCount: scan.filesVisited, sourceFileCount: scan.files.filter((file) => file.category === "source").length, testFileCount: scan.files.filter((file) => file.category === "test").length, parsedFileCount: parsedCount },
		coverage: { maxDepth, maxDirs, maxFilesPerDir, maxSymbolsPerFile, truncated: scan.truncated, excludedDirs: scan.excludedDirs },
		diagnostics: scan.diagnostics,
		limitations: [tier === "shape" ? "Shape overview is filesystem evidence only; use tier:'files' or code_intel_file_outline for declarations." : "File-tier overview is capped per directory and per file; use code_intel_file_outline for a complete single-file outline."],
		elapsedMs: Date.now() - started,
	};
}

function defaultTestPaths(scan: ScanResult): string[] {
	const dirs = new Set<string>();
	function visit(dir: ScanDirectory): void {
		const base = path.posix.basename(dir.path).toLowerCase();
		if (["test", "tests", "__tests__", "spec", "integration", "queries", "gtest"].includes(base)) dirs.add(dir.path);
		for (const child of dir.children) visit(child);
	}
	for (const dir of scan.directories) visit(dir);
	return [...dirs].sort();
}

const LOW_SIGNAL_PATH_TERMS = new Set(["apply", "function", "functions", "range", "over", "time", "timeseries", "test", "tests", "query", "queries"]);

function tokensForPath(file: string): string[] {
	const stem = path.posix.basename(file).replace(/\.[^.]+$/, "");
	return [...new Set(stem.split(/[^A-Za-z0-9]+|(?=[A-Z])/).map((part) => part.toLowerCase()).filter((part) => part.length >= 3 && !LOW_SIGNAL_PATH_TERMS.has(part)))];
}

function isNoisyTestArtifact(file: string): boolean {
	return /(^|\/)__pycache__(\/|$)/.test(file) || /\.(pyc|pyo|log|tmp|out|err)$/i.test(file) || /(^|\/)node\/logs\//.test(file);
}

function candidateScore(file: string, targetPath: string | undefined, terms: string[]): { score: number; evidence: Record<string, unknown>[] } {
	let score = 0;
	const evidence: Record<string, unknown>[] = [];
	const seenEvidence = new Set<string>();
	const addEvidence = (kind: string, term: string, points: number): void => {
		const key = `${kind}\0${term}`;
		if (seenEvidence.has(key)) return;
		seenEvidence.add(key);
		score += points;
		evidence.push({ kind, term });
	};
	const fileLower = file.toLowerCase();
	if (targetPath) {
		const targetStem = path.posix.basename(targetPath).replace(/\.[^.]+$/, "").toLowerCase();
		if (fileLower.includes(targetStem)) addEvidence("path_basename", targetStem, 6);
		for (const token of tokensForPath(targetPath)) {
			if (fileLower.includes(token)) addEvidence("path_term", token, 2);
		}
	}
	for (const term of terms) {
		if (LOW_SIGNAL_PATH_TERMS.has(term.toLowerCase())) continue;
		if (fileLower.includes(term.toLowerCase())) addEvidence("path_term", term, 3);
	}
	return { score, evidence };
}

function literalMatches(file: ScanFile, terms: string[], maxMatches: number): Record<string, unknown>[] {
	const evidence: Record<string, unknown>[] = [];
	let source: string;
	try {
		source = fs.readFileSync(file.absolutePath, "utf-8");
	} catch {
		return evidence;
	}
	const lines = source.split(/\r?\n/);
	for (const term of terms) {
		if (evidence.length >= maxMatches) break;
		const needle = term.toLowerCase();
		for (let index = 0; index < lines.length; index++) {
			if (lines[index].toLowerCase().includes(needle)) {
				evidence.push({ kind: "literal_match", term, line: index + 1 });
				break;
			}
		}
	}
	return evidence;
}

export async function runTestMap(params: CodeIntelTestMapParams, repoRoot: string, config: CodeIntelConfig, signal?: AbortSignal): Promise<Record<string, unknown>> {
	const started = Date.now();
	const maxResults = normalizePositiveInteger(params.maxResults, Math.min(config.maxResults, 50), 1, 500);
	const maxLiteralMatches = normalizePositiveInteger(params.maxLiteralMatches, 5, 0, 50);
	const timeoutMs = normalizePositiveInteger(params.timeoutMs, config.queryTimeoutMs, 1_000, 600_000);
	const diagnostics: string[] = [];
	let safePath: string | undefined;
	if (params.path) {
		try {
			safePath = ensureInsideRoot(repoRoot, params.path);
		} catch (error) {
			diagnostics.push(`${params.path}: ${error instanceof Error ? error.message : String(error)}`);
		}
	}
	const explicitTerms = [...new Set([...normalizeStringArray(params.symbols), ...normalizeStringArray(params.names)].filter((term) => term.length >= 2))];
	const terms = [...new Set([...explicitTerms, ...(safePath ? tokensForPath(safePath) : [])].filter((term) => term.length >= 2))];
	const shapeScan = scanRepo(repoRoot, { paths: ["."], maxDepth: 4, maxDirs: 500, maxFilesPerDir: 0, includeVendor: false, includeGenerated: false, timeoutMs }, signal);
	const testRoots = normalizeStringArray(params.testPaths).length > 0 ? normalizeStringArray(params.testPaths) : defaultTestPaths(shapeScan);
	const scan = scanRepo(repoRoot, { paths: testRoots.length > 0 ? testRoots : ["tests", "test"], maxDepth: 12, maxDirs: 1_000, maxFilesPerDir: 1_000, includeVendor: false, includeGenerated: false, timeoutMs }, signal);
	const candidates: Array<Record<string, unknown> & { score: number; evidence: Record<string, unknown>[] }> = [];
	for (const file of scan.files) {
		if (isNoisyTestArtifact(file.path)) continue;
		if (file.category !== "test" && !TEST_DIR_PATTERN.test(file.path)) continue;
		const pathEvidence = candidateScore(file.path, safePath, terms);
		const literalEvidence = literalMatches(file, explicitTerms, maxLiteralMatches);
		const evidence = [...pathEvidence.evidence, ...literalEvidence];
		const score = pathEvidence.score + literalEvidence.length * 5;
		if (score <= 0 || evidence.length === 0) continue;
		candidates.push({ file: file.path, language: file.language, category: file.category, score, evidence });
	}
	candidates.sort((left, right) => right.score - left.score || String(left.file).localeCompare(String(right.file)));
	const outputCandidates = candidates.slice(0, maxResults);
	const output: Record<string, unknown> = {
		ok: true,
		repoRoot,
		target: { path: safePath, symbols: normalizeStringArray(params.symbols), names: normalizeStringArray(params.names) },
		candidates: outputCandidates,
		summary: { candidateCount: candidates.length, returnedCount: outputCandidates.length, testRootsSearched: testRoots },
		coverage: { truncated: candidates.length > maxResults, maxResults, maxLiteralMatches, searchedFileCount: scan.files.length, excludedDirs: { ...shapeScan.excludedDirs, ...scan.excludedDirs } },
		diagnostics: [...diagnostics, ...shapeScan.diagnostics, ...scan.diagnostics],
		limitations: ["Test maps are evidence-ranked candidates, not exhaustive coverage proof. Non-code tests may only match path or literal terms."],
		elapsedMs: Date.now() - started,
	};
	if (params.confirmReferences === "gopls" || params.confirmReferences === "typescript" || params.confirmReferences === "clangd") {
		const outline = safePath ? await runFileOutline({ path: safePath, maxSymbols: 20, detail: "locations" }, repoRoot, config, signal) : undefined;
		const roots = Array.isArray(outline?.declarations) ? (outline.declarations as Record<string, unknown>[]).filter((row) => normalizeStringArray(params.symbols).includes(String(row.name))).map((row) => ({ name: String(row.name), file: safePath ?? "", language: String(outline?.language ?? ""), kind: String(row.kind ?? "definition"), line: Number(row.line ?? 1), column: Number(row.column ?? 1), endLine: Number(row.endLine ?? row.line ?? 1), endColumn: Number(row.endColumn ?? row.column ?? 1) })) : [];
		output.referenceConfirmation = await runReferenceConfirmation(params.confirmReferences, roots, repoRoot, { maxRoots: params.maxReferenceRoots, maxResults: params.maxReferenceResults, timeoutMs, includeDeclarations: false }, config, signal);
	}
	return output;
}
